language: java
sudo: false

matrix:
  include:

    #==============================
    #
    #     linux open
    #
    #==============================

    - os: linux
      dist: bionic
      compiler: javac
      jdk: openjdk11
      env: JAVA_IMPLEMENTATION=java-11-openjdk-amd64

before_install:
  - eval
  - mkdir beerReduceBin
  - chmod 711 hadoop-2.8.0/bin/hadoop

before_script:
  - export JAVA_HOME=/usr/lib/jvm/${JAVA_IMPLEMENTATION}
  - export HADOOP_CLASSPATH=$JAVA_HOME/lib/tools.jar
  - export HADOOP_HOME=$PWD/hadoop-2.8.0
  - export PATH=$PATH:$HADOOP_HOME/bin/:$JAVA_HOME/bin/
  - ls /usr/lib/jvm/

script:
  - hadoop com.sun.tools.javac.Main -d beerReduceBin src/BestIPA.java
  - jar -cvf beerReduceBin/bestIPA.jar -C beerReduceBin/ .
  - hadoop com.sun.tools.javac.Main -d beerReduceBin src/DarkestBeer.java
  - jar -cvf beerReduceBin/darkestBeer.jar -C beerReduceBin/ .
